server:
  port: 8090
  servlet:
    context-path: /monitoring-tool-users-ms



spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring_db
    driver-class-name: org.postgresql.Driver
    username: monitoring-user
    password: monitoring
    hikari:
      schema: public

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    root: INFO

domain:
  password:
    notification:
      url: http://localhost:8090
      expires: 10

jwt:
  expiration: 3600000
  secret: ${SECRET_TOKEN:6IBwdiQm6JUC7nCL8PEm9Y8O7D41XYoMlnPD4a3cXTd5AHEgQjdRZAsiao5ysm9hquHjvIuigm4ACGzwTEFC0A==}

admin:
  email: juliansmartinez@unicauca.edu.co
  name: Paula Peña
  lastname: App
  document: 1061226854
  phone: 3000000000